# -*- coding: utf-8 -*-
"""drone-detection-software

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGLni0LHsTAJPdlzLi8JadDTCHDFDq1J
"""

!nvidia-smi

!pip install ultralytics -q

# Upload dataset.zip
from google.colab import files
import zipfile
import os

print("Please upload your dataset.zip file...")
uploaded = files.upload()

# Unzip
for filename in uploaded.keys():
    print(f'Unzipping {filename}...')
    with zipfile.ZipFile(filename, 'r') as zip_ref:
        zip_ref.extractall('/content/')
    print('Done!')

# Verify structure
!ls -la /content/data/
!ls -la /content/data/images/train/ | head -5
!ls -la /content/data/labels/train/ | head -5

# Update config.yaml to use Colab paths
config_content = """path: /content/data
train: images/train
val: images/train

# Classes
names:
  0: car
  1: bus
  2: truck
  3: boat
  4: aircraft
  5: military
"""

with open('/content/data/config.yaml', 'w') as f:
    f.write(config_content)

print("Config updated!")
!cat /content/data/config.yaml

from ultralytics import YOLO

# Load pretrained model
model = YOLO("yolo11n.pt")

# Train
results = model.train(
    data="/content/data/config.yaml",
    epochs=100,
    imgsz=640,
    batch=16,
    name="object-detection-v1",
    patience=20,
    save=True,
    device=0,  # GPU
    workers=2,
    project="/content/runs/train",
    exist_ok=True,
    pretrained=True,
    verbose=True,
)

print("\nTraining complete")
print(f"Best model saved at: /content/runs/train/object-detection-v1/weights/best.pt")

# Display training graphs
from IPython.display import Image, display

print("Training Results:")
display(Image('/content/runs/train/mclaren_tracker/results.png'))

print("\nConfusion Matrix:")
display(Image('/content/runs/train/mclaren_tracker/confusion_matrix.png'))

# Print metrics
import pandas as pd
results_csv = pd.read_csv('/content/runs/train/mclaren_tracker/results.csv')
print("\nFinal Metrics:")
print(results_csv.tail())

# Test on a sample image
model = YOLO('/content/runs/train/mclaren_tracker/weights/best.pt')

# Upload a test image
print("Upload a test image from your video...")
test_img = files.upload()

# Run detection
for filename in test_img.keys():
    results = model(filename, conf=0.25)
    results[0].show()
    print(f"Detections: {len(results[0].boxes)}")

# Download the trained model to
from google.colab import files
import shutil

# Zip the weights folder
shutil.make_archive('/content/trained_model', 'zip', '/content/runs/train/mclaren_tracker/weights')

print("Downloading trained model...")
files.download('/content/trained_model.zip')

# In Colab: Create a Google Drive link (prevents google from thinking file is a virus)
from google.colab import drive
drive.mount('/content/drive')

# Copy the model to Google Drive
!cp /content/runs/train/mclaren_tracker/weights/best.pt /content/drive/MyDrive/

print("Model saved to Google Drive")
print("Download from: Google Drive > MyDrive > best.pt")
